openapi: 3.0.0
info:
  title: Luxury Clothes Backend
  contact:
    name: Alexey Poltoradnev
    email: poltoradnevone@gmail.com
  version: '1.0'
servers:
  - url: https://project-landc.herokuapp.com/api
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/RegisterRequest'
                - example:
                    username: Bob Ross
                    email: bobross@gmail.com
                    password: '123456'
                    confirmPassword: '123456'
            example:
              username: Bob Ross
              email: bobross@gmail.com
              password: '123456'
              confirmPassword: '123456'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/LoginRequest'
                - example:
                    email: bobross@gmail.com
                    password: '123456'
            example:
              email: bobross@gmail.com
              password: '123456'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/logout:
    get:
      tags:
        - Auth
      summary: Logout
      operationId: Logout
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /auth/me:
    get:
      tags:
        - Auth
      summary: Me
      operationId: Me
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products:
    get:
      tags:
        - Products
      summary: Get Products
      operationId: GetProducts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/178328fd-5c51-43ba-9c03-a3f98d6c74f5:
    get:
      tags:
        - Products
      summary: Get Product
      operationId: GetProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/categories:
    get:
      tags:
        - Products
      summary: Get Categories
      operationId: GetCategories
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/search:
    get:
      tags:
        - Products
      summary: Search Products
      operationId: SearchProducts
      parameters:
        - name: page
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 1
        - name: pageSize
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 20
        - name: search
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: рубашка
        - name: category
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: рубашки
        - name: order
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: desc
        - name: price
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: 2000-3000
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/favourites:
    get:
      tags:
        - Products
      summary: Get Favourites
      operationId: GetFavourites
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /products/favourites/ff005981-c0ce-4ddd-ae40-843411e92a85:
    post:
      tags:
        - Products
      summary: Toggle Favourite
      operationId: ToggleFavourite
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /orders:
    post:
      tags:
        - Orders
      summary: Create Order
      operationId: CreateOrder
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateOrderRequest'
                - example:
                    email_address: bobross@gmail.com
                    full_name: Bob Ross
                    address: berezovaya 11
                    country: Russia
                    postal_code: 443080
                    city: Samara
                    payment_method: Stripe
                    items_price: 5799
                    shipping_price: 0
                    tax_price: 0
                    total_price: 5799
                    products:
                      - id: ff005981-c0ce-4ddd-ae40-843411e92a85
                        quantity: 1
            example:
              email_address: bobross@gmail.com
              full_name: Bob Ross
              address: berezovaya 11
              country: Russia
              postal_code: 443080
              city: Samara
              payment_method: Stripe
              items_price: 5799
              shipping_price: 0
              tax_price: 0
              total_price: 5799
              products:
                - id: ff005981-c0ce-4ddd-ae40-843411e92a85
                  quantity: 1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
        - Orders
      summary: Get My Orders
      operationId: GetMyOrders
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /orders/d93bcce8-70d6-4ff2-a6a4-54ea83a3035f:
    get:
      tags:
        - Orders
      summary: Get Order
      operationId: GetOrder
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /orders/3e1988f1-0691-494b-a0c8-93730cabdeb4:
    delete:
      tags:
        - Orders
      summary: Delete Order
      operationId: DeleteOrder
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /orders/payment/d93bcce8-70d6-4ff2-a6a4-54ea83a3035f:
    patch:
      tags:
        - Orders
      summary: Update Payment
      operationId: UpdatePayment
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /orders/delivery/d93bcce8-70d6-4ff2-a6a4-54ea83a3035f:
    patch:
      tags:
        - Orders
      summary: Update Delivery
      operationId: UpdateDelivery
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /payment/create-payment-intent:
    post:
      tags:
        - Payment
      summary: Create Payment Intent
      operationId: CreatePaymentIntent
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreatePaymentIntentRequest'
                - example:
                    amount: 200
                    currency: Rub
            example:
              amount: 200
              currency: Rub
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /upload:
    post:
      tags:
        - Upload
      summary: Upload Image
      operationId: UploadImage
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /upload/dk8xuzchkaqkgspldrzr:
    delete:
      tags:
        - Upload
      summary: Delete Image
      operationId: DeleteImage
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /cart:
    post:
      tags:
        - Cart
      summary: Add Product To Cart
      operationId: AddProductToCart
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/AddProductToCartRequest'
                - example:
                    product:
                      id: ff005981-c0ce-4ddd-ae40-843411e92a85
            example:
              product:
                id: ff005981-c0ce-4ddd-ae40-843411e92a85
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
        - Cart
      summary: Get Cart
      operationId: GetCart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
        - Cart
      summary: Clear Cart
      operationId: ClearCart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /cart/ff005981-c0ce-4ddd-ae40-843411e92a85:
    delete:
      tags:
        - Cart
      summary: Remove Product
      operationId: RemoveProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /cart/ff005981-c0ce-4ddd-ae40-843411e92a85/increment:
    post:
      tags:
        - Cart
      summary: Increment Product
      operationId: IncrementProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /cart/ff005981-c0ce-4ddd-ae40-843411e92a85/decrement:
    post:
      tags:
        - Cart
      summary: Decrement Product
      operationId: DecrementProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /messages:
    post:
      tags:
        - Messages
      summary: Send Message
      operationId: SendMessage
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/SendMessageRequest'
                - example:
                    subject: Доставка
                    message: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi excepturi deleniti expedita, consequuntur quibusdam commodi sapiente asperiores maiores quo vel recusandae fugiat optio debitis voluptatem nobis. Quia odio dolorum, tempora atque ullam sapiente corporis commodi quo minima in dicta? Dicta, in delectus ratione non nulla ea. Possimus sit voluptatum velit?
                    isSend: true
            example:
              subject: Доставка
              message: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi excepturi deleniti expedita, consequuntur quibusdam commodi sapiente asperiores maiores quo vel recusandae fugiat optio debitis voluptatem nobis. Quia odio dolorum, tempora atque ullam sapiente corporis commodi quo minima in dicta? Dicta, in delectus ratione non nulla ea. Possimus sit voluptatum velit?
              isSend: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
        - Messages
      summary: Get Messages
      operationId: GetMessages
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /messages/1be719d6-98a8-4f7a-b74f-93d6cdae2545:
    patch:
      tags:
        - Messages
      summary: Update Message
      operationId: UpdateMessage
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UpdateMessageRequest'
                - example:
                    subject: Доставка
                    message: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi excepturi deleniti expedita, consequuntur quibusdam commodi sapiente asperiores maiores quo vel recusandae fugiat optio debitis voluptatem nobis. Quia odio dolorum, tempora atque ullam sapiente corporis commodi quo minima in dicta? Dicta, in delectus ratione non nulla ea. Possimus sit voluptatum velit?
                    isSend: true
            example:
              subject: Доставка
              message: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi excepturi deleniti expedita, consequuntur quibusdam commodi sapiente asperiores maiores quo vel recusandae fugiat optio debitis voluptatem nobis. Quia odio dolorum, tempora atque ullam sapiente corporis commodi quo minima in dicta? Dicta, in delectus ratione non nulla ea. Possimus sit voluptatum velit?
              isSend: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
        - Messages
      summary: Delete Message
      operationId: DeleteMessage
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      required:
        - username
        - email
        - password
        - confirmPassword
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
      example:
        username: Bob Ross
        email: bobross@gmail.com
        password: '123456'
        confirmPassword: '123456'
    LoginRequest:
      title: LoginRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: bobross@gmail.com
        password: '123456'
    CreateOrderRequest:
      title: CreateOrderRequest
      required:
        - email_address
        - full_name
        - address
        - country
        - postal_code
        - city
        - payment_method
        - items_price
        - shipping_price
        - tax_price
        - total_price
        - products
      type: object
      properties:
        email_address:
          type: string
        full_name:
          type: string
        address:
          type: string
        country:
          type: string
        postal_code:
          type: integer
          format: int32
        city:
          type: string
        payment_method:
          type: string
        items_price:
          type: integer
          format: int32
        shipping_price:
          type: integer
          format: int32
        tax_price:
          type: integer
          format: int32
        total_price:
          type: integer
          format: int32
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
          description: ''
      example:
        email_address: bobross@gmail.com
        full_name: Bob Ross
        address: berezovaya 11
        country: Russia
        postal_code: 443080
        city: Samara
        payment_method: Stripe
        items_price: 5799
        shipping_price: 0
        tax_price: 0
        total_price: 5799
        products:
          - id: ff005981-c0ce-4ddd-ae40-843411e92a85
            quantity: 1
    Product:
      title: Product
      required:
        - id
        - quantity
      type: object
      properties:
        id:
          type: string
        quantity:
          type: integer
          format: int32
      example:
        id: ff005981-c0ce-4ddd-ae40-843411e92a85
        quantity: 1
    CreatePaymentIntentRequest:
      title: CreatePaymentIntentRequest
      required:
        - amount
        - currency
      type: object
      properties:
        amount:
          type: integer
          format: int32
        currency:
          type: string
      example:
        amount: 200
        currency: Rub
    AddProductToCartRequest:
      title: AddProductToCartRequest
      required:
        - product
      type: object
      properties:
        product:
          allOf:
            - $ref: '#/components/schemas/Product1'
            - {}
      example:
        product:
          id: ff005981-c0ce-4ddd-ae40-843411e92a85
    Product1:
      title: Product1
      required:
        - id
      type: object
      properties:
        id:
          type: string
      example:
        id: ff005981-c0ce-4ddd-ae40-843411e92a85
    SendMessageRequest:
      title: SendMessageRequest
      required:
        - subject
        - message
        - isSend
      type: object
      properties:
        subject:
          type: string
        message:
          type: string
        isSend:
          type: boolean
      example:
        subject: Доставка
        message: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi excepturi deleniti expedita, consequuntur quibusdam commodi sapiente asperiores maiores quo vel recusandae fugiat optio debitis voluptatem nobis. Quia odio dolorum, tempora atque ullam sapiente corporis commodi quo minima in dicta? Dicta, in delectus ratione non nulla ea. Possimus sit voluptatum velit?
        isSend: true
    UpdateMessageRequest:
      title: UpdateMessageRequest
      required:
        - subject
        - message
        - isSend
      type: object
      properties:
        subject:
          type: string
        message:
          type: string
        isSend:
          type: boolean
      example:
        subject: Доставка
        message: Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi excepturi deleniti expedita, consequuntur quibusdam commodi sapiente asperiores maiores quo vel recusandae fugiat optio debitis voluptatem nobis. Quia odio dolorum, tempora atque ullam sapiente corporis commodi quo minima in dicta? Dicta, in delectus ratione non nulla ea. Possimus sit voluptatum velit?
        isSend: true
security:
  - {}
tags:
  - name: Auth
  - name: Products
  - name: Orders
  - name: Payment
  - name: Upload
  - name: Cart
  - name: Messages
