"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
const cart_1 = require("../controllers/cart");
router.get('/', cart_1.getCart);
router.post('/', cart_1.addProductToCart);
router.post('/:id/increment', cart_1.incrementProduct);
router.post('/:id/decrement', cart_1.decrementProduct);
router.delete('/', cart_1.clearCart);
router.delete('/:id', cart_1.removeProduct);
exports.default = router;
